---
include:
  - project: bauwatch/tools/pipelines
    ref: v1.1
    file: default.gitlab-ci.yml

default:
    image: $CI_REGISTRY/bauwatch/tools/docgen:BTH-58-create-latex-template

# Example build
build:
  stage: build
  script:
    - latexmk -xelatex src/main.tex
    - make check-clean
